repos:
-   repo: https://github.com/ambv/black
    rev: 23.7.0
    hooks:
    - id: black
      exclude: ^.*\/migrations\/.*
      language_version: python3
-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
    - id: isort
      args: ["--profile", "black"]
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    - id: flake8
      exclude: ^.*\/migrations\/.*
