[tool.black]
line-length = 79
include = '\.pyi?$'
force-exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | build
    | dist
    | docs
    | ^migrations/

  )/
  | fabfile.py
  | local.py
  | local_test.py
)
'''