version: '3'

services:
  backend:
    container_name: foodgram_backend
    image: glfmn/foodgram_backend
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media/
    env_file:
     - .env.dev
    depends_on:
      - db
  db:
    container_name: foodgram-postgres-db
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
     - .env.dev
    restart: always

  frontend:
    container_name: foodgram_frontend
    image: glfmn/foodgram_frontend
    volumes:
      - ./frontend/:/app/result_build/
    depends_on:
      - backend
      - db
  gateway:
    image: glfmn/foodgram_gateway
    ports:
      - 8888:80
    volumes:
      - ./frontend/build:/usr/share/nginx/html/
      - static_volume:/etc/nginx/html/static/
      - media_volume:/usr/src/app/media/      
      - ./docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
      - frontend
    restart: always

volumes:
  postgres_data:
  static_volume:
  media_volume: