# version: '3.3'
# volumes:
#   pg_data:
#   static:
#   media:
#   frontend_static:


# services:
#   db:
#     image: postgres:13.0 -alpine
#     volumes:
#       - pg_data:/var/lib/postgresql/data
#     env_file:
#       - ./.env

#   backend:
#     volumes: -static:/app/static -media:/app/media
#     depends_on:
#       - db
#     env_file:
#       - ./.env

#   frontend:
#     build:
#       context: ../frontend
#       dockerfile: Dockerfile
#     volumes:
#       - frontend_static:/app/result_build/

#   nginx:
#     image: nginx:1.19.3
#     ports:
#       - "80:80"
#     volumes:
#       - static:/var/html/static/
#       - media:/var/html/media/
#       - frontend_static:/usr/share/nginx/html/
#       - ./nginx.conf:/etc/nginx/conf.d/default.conf
#       - ../docs/:/usr/share/nginx/html/api/docs/
#     depends_on:
#       - frontend
#       - backend
