version: '3'

volumes:
  postgres_data:
  static_volume:
  media_volume:

services:
  backend:
    container_name: foodgram-backend
    build: ../backend/
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/share/nginx/html/media

    env_file:
     - ../infra/.env.dev
    depends_on:
      - db
  db:
    container_name: foodgram-postgres-db
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
     - ../infra/.env.dev
    restart: always
  frontend:
    container_name: foodgram-frontend
    build: ../frontend/ 
    volumes:
      - ./frontend/:/app/result_build/
    depends_on:
      - backend
      - db

  nginx:
    container_name: foodgram_nginx
    build: ../nginx
    ports:
      - 8888:80
    volumes:
      - static_volume:/etc/nginx/html/static
      - media_volume:/usr/share/nginx/html/media;
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - ./docs/:/usr/share/nginx/html/api/docs/
    depends_on:
      - backend
    restart: always



 