version: '3'

volumes:
  pg_data:
  static:
  media:


services:
  db:
    image: postgres:13.0 -alpine
    env_file: ../.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  frontend:
    #env_file: .env
    build:
      context: ../frontend/
      dockerfile: Dockerfile
    #command: cp -r /app/build/. /frontend_static/
    volumes:
      - ..frontend/:/app/result_build
  nginx:
    image: nginx:1.19.3
    #env_file: .env
    ports:
      - 80:80
    volumes:
      - static:/static
      - media:/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
    #depends_on:
    #  - backend
