version: '3'

volumes:
  static:
  media:


services:
  backend:
    build: ../backend/
    volumes:
      - static:/static
      - media:/app/media
      - ../backend/db.sqlite3:/data/db.sqlite3
    ports:
      - "8000:8000"
    environment:
      - DJANGO_SETTINGS_MODULE=foodgram.settings
      - DEBUG=true

  frontend:
    build:
      context: ../frontend/
      dockerfile: Dockerfile
    command: npm start
    volumes:
      - static:/result_build
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development

  nginx:
    image: nginx:1.19.3
    ports:
      - "80:80"
    volumes:
      - static:/static
      - media:/app/media
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
    depends_on:
      - backend
