# Generated by Django 3.2.9 on 2023-08-18 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_shopping_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_subscribed',
        ),
    ]
