# Generated by Django 3.2.9 on 2023-08-22 19:14

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_subscription_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="subscriptions",
            field=models.ManyToManyField(
                blank=True,
                default=False,
                editable=False,
                related_name="subscribers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Подписан ли текущий пользователь на этого",
            ),
        ),
        migrations.DeleteModel(
            name="Subscription",
        ),
    ]
