# Generated by Django 3.2.9 on 2023-08-22 22:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_subscription"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="subscriptions",
        ),
    ]
