# Generated by Django 3.2.9 on 2023-08-22 22:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0011_remove_user_subscriptions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="subscriber",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subscriptions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Подписчик",
            ),
        ),
    ]
